### ISSUE TITLE
Home Page Redesign

### ISSUE THREAD

**Issue by sopermaf** [sopermaf/polyglossa#49]
[Polyglossa Home Page.pdf](https://github.com/sopermaf/polyglossa/files/4932479/Polyglossa.Home.Page.pdf)

**TODO**
- [x] Banner recolour and new headers
- [x] Upcoming seminar calendar section
- [x] Select highlighted seminars should be shown on home page
- [x] Seminars link to their match on seminar page for full description
