### ISSUE TITLE
Version 1 - Todo Checklist

### ISSUE THREAD

**Issue by sopermaf** [sopermaf/polyglossa#9]
This is a list of the tasks to be completed for version 1 of `Polyglossa` and their progress

# Website
### Models
- [X] Student Model
- [ ] Seminar Slot Model
  - [ ]  Pricing (per activity or per hour?)
  - [ ]  Timezones
  - [X]  Slot clashes
- [X]  Activity Model  (Pricing issue)

### Requests
- [X]  Send form page and relevant data
- [ ]  Add in Authentication (csrf_exempt problem)
- [X]  parsing
- [X]  validation
- [X]  saving model
- [ ]  Integration with payment services (Paypal)
- [ ]  Payment confirmation

### Admin Features
- [X]  Seminar Creation
- [X]  Slot Creation
- [ ]  Send mass email with live link

### Server Jobs
- [ ]  Email confirmation

## Front End
- [ ]  Description Pages
- [ ]  Home Page
- [ ]  Seminar Sign up Form

# Deployment
- [ ]  Online VPS with dockerfiles
- [ ]  Manage DB backups
- [ ]  Deployment pipeline from Github
  - [ ] Dockerisation of Django and Vue
- [ ]  Testing
  - [ ]  Full end to end testing
